<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AgreeTC</name>
   <tag></tag>
   <elementGuidId>a3d909f5-01c2-4369-85da-f98aeee3080c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@data-testid=&quot;co-terms-and-conditions-checkbox-tac&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@data-testid=&quot;co-terms-and-conditions-checkbox-tac&quot;]</value>
   </webElementProperties>
</WebElementEntity>
