<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Salutation(Mr)</name>
   <tag></tag>
   <elementGuidId>e190788a-b68e-4f1a-a41d-92e00f09e3f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@for=&quot;co_payment_address-salutationCode-radio-id-0&quot;]</value>
   </webElementProperties>
</WebElementEntity>
