<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickOnOrderAsGuest</name>
   <tag></tag>
   <elementGuidId>8c98cf34-9e92-461a-a522-378dd01a744f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@data-testid=&quot;co-order-process-login-guest-user-cta&quot;]</value>
   </webElementProperties>
</WebElementEntity>
